### ISSUE TITLE
Program with device code in multiple translation units fails on CUDA

### ISSUE THREAD

**Issue by sergey-semenov** [intel/llvm#4156]
**Describe the bug**
A simple program with device code in multiple translation units fails in runtime with CUDA_ERROR_INVALID_IMAGE as of https://github.com/intel/llvm/pull/3735

**To Reproduce**
h.hpp:

```
#include <CL/sycl.hpp>

void submit_kernelB();
```
b.cpp
```
#include "h.hpp"

class KernelNameB;

void submit_kernelB() {
  sycl::queue q;
  q.submit([&](sycl::handler &cgh) { cgh.single_task<KernelNameB>([]() {}); });
}
```
main.cpp:
```
#include "h.hpp"
#include <CL/sycl.hpp>

class KernelNameA;
void submit_kernelA() {
  sycl::queue q;
  q.submit([&](sycl::handler &cgh) { cgh.single_task<KernelNameA>([]() {}); });
}

int main() { submit_kernelA(); }
```
```
clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda-sycldevice main.cpp b.cpp
./a.out
```
This reproducer fails with CUDA_ERROR_INVALID_IMAGE, note that compiling this results in 2 device images as of https://github.com/intel/llvm/pull/3735, but in only one with it reverted. The error disappears once the number of device images in the application is reduced to 1 (either by moving `submit_kernelB` to the same translation unit as `submit_kernelA`, by using `-fsycl-device-code-split=off` or by reverting https://github.com/intel/llvm/pull/3735).

**Environment:**

- OS: Linux
- Target device and vendor: CUDA, Titan RTX.
- DPC++ version: e9d308e5fc70fd4ca80dfb47a72fbc0b375c11ee
- Dependencies version: CUDA 10.1

**Comment by bader** [comment]
@sergey-semenov, I think this issue is already fixed by https://github.com/intel/llvm/commit/351af240e693c4e8348c08cc5f08e8c389753ec2. Could you check with newer version of the compiler?

**Comment by bader** [comment]
https://github.com/intel/llvm/issues/4088 and https://github.com/intel/llvm/issues/4079 seems to be about the same problem.

**Comment by sergey-semenov** [comment]
Ah, I specified the guilty commit rather than the version of the compiler I reproduced this on. This problem is still reproducible on https://github.com/intel/llvm/commit/e9d308e5fc70fd4ca80dfb47a72fbc0b375c11ee, so it seems https://github.com/intel/llvm/commit/351af240e693c4e8348c08cc5f08e8c389753ec2 didn't address this.

**Comment by bader** [comment]
Okay, thanks for the update.
Maybe https://github.com/intel/llvm/pull/4107 will help this case.

**Comment by Michoumichmich** [comment]
@sergey-semenov can you try [that](https://github.com/intel/llvm/issues/4088#issuecomment-877622036)?

**Comment by sergey-semenov** [comment]
@Michoumichmich Reverting the driver part of https://github.com/intel/llvm/commit/f7ce532d622dc26eddd25f87faec0ff35dc0c2e9 didn't help, the reproducer is still failing as before.

**Comment by bader** [comment]
> A simple program with device code in multiple translation units fails in runtime with CUDA_ERROR_INVALID_IMAGE as of #3735

@steffenlarsen, could you take a look, please? It looks like #3735 introduced a significant functional regression.

**Comment by steffenlarsen** [comment]
https://github.com/intel/llvm/pull/4107 introduces a better solution for the driver changes in #3735. @sergey-semenov would you be able to check if that solves this issue?

**Comment by sergey-semenov** [comment]
This is indeed resolved by #4107
