### ISSUE TITLE
[SYCL] CUDA LLVM Test Suite pre-commit task failure

### ISSUE THREAD

**Issue by maarquitos14** [intel/llvm#8040]
Test  `SYCL :: BFloat16/bfloat16_builtins.cpp` fails with following output:

```
******************** TEST 'SYCL :: BFloat16/bfloat16_builtins.cpp' FAILED ********************
Script:
--
: 'RUN: at line 7';    /__w/llvm/llvm/toolchain/bin/clang++      -fsycl -fsycl-targets=nvptx64-nvidia-cuda /__w/llvm/llvm/llvm_test_suite/SYCL/BFloat16/bfloat16_builtins.cpp -o /__w/llvm/llvm/build/SYCL/BFloat16/Output/bfloat16_builtins.cpp.tmp.out -Xsycl-target-backend --cuda-gpu-arch=sm_80
: 'RUN: at line 8';   /__w/llvm/llvm/build/SYCL/BFloat16/Output/bfloat16_builtins.cpp.tmp.out
--
Exit Code: -6

Command Output (stdout):
--
$ ":" "RUN: at line 7"
note: command had no output on stdout or stderr
$ "/__w/llvm/llvm/toolchain/bin/clang++" "-fsycl" "-fsycl-targets=nvptx64-nvidia-cuda" "/__w/llvm/llvm/llvm_test_suite/SYCL/BFloat16/bfloat16_builtins.cpp" "-o" "/__w/llvm/llvm/build/SYCL/BFloat16/Output/bfloat16_builtins.cpp.tmp.out" "-Xsycl-target-backend" "--cuda-gpu-arch=sm_80"
# command stderr:
clang-16: warning: CUDA version 11.7 is only partially supported [-Wunknown-cuda-version]

$ ":" "RUN: at line 8"
note: command had no output on stdout or stderr
$ "/__w/llvm/llvm/build/SYCL/BFloat16/Output/bfloat16_builtins.cpp.tmp.out"
# command stderr:
bfloat16_builtins.cpp.tmp.out: /__w/llvm/llvm/llvm_test_suite/SYCL/BFloat16/bfloat16_builtins.cpp:269: int main(): Assertion `err == 0' failed.

error: command failed with exit status: -6
```
Complete output can be seen in this [link](https://github.com/intel/llvm/actions/runs/3950482477/jobs/6763578027).

**Comment by MrSidims** [comment]
My best guess, that https://github.com/intel/llvm/pull/7959 also required the test update, https://github.com/intel/llvm-test-suite/pull/1495. [In this PR](https://github.com/intel/llvm/pull/7917) I have started 'verify with' to check this claim.

**Comment by bader** [comment]
> My best guess, that #7959 also required the test update, [intel/llvm-test-suite#1495](https://github.com/intel/llvm-test-suite/pull/1495).

Pre-commit for https://github.com/intel/llvm/pull/7959 has passed w/o llvm-test-suite modifications. 🤔

**Comment by MrSidims** [comment]
> > My best guess, that #7959 also required the test update, [intel/llvm-test-suite#1495](https://github.com/intel/llvm-test-suite/pull/1495).
> 
> Pre-commit for #7959 has passed w/o llvm-test-suite modifications. 🤔

Well, I still don't really understand the root cause of the issue, but in https://github.com/intel/llvm/pull/7917 'verify with https://github.com/intel/llvm-test-suite/pull/1495 ' has passed

**Comment by aelovikov-intel** [comment]
https://github.com/intel/llvm/pull/8058 has the following (new?) fail on this same test with HIP backend (https://github.com/intel/llvm/actions/runs/3962690653/jobs/6790110891):

```
note: command had no output on stdout or stderr
$ "/__w/llvm/llvm/toolchain/bin/clang++" "-Xsycl-target-backend=amdgcn-amd-amdhsa" "--offload-arch=gfx1031" "-fsycl" "-fsycl-targets=amdgcn-amd-amdhsa" "/__w/llvm/llvm/llvm_test_suite/SYCL/BFloat16/bfloat16_builtins.cpp" "-o" "/__w/llvm/llvm/build/SYCL/BFloat16/Output/bfloat16_builtins.cpp.tmp.out"
# command stderr:
lld: error: undefined hidden symbol: __devicelib_ConvertFToBF16INTEL
>>> referenced by lto.tmp:(typeinfo name for sycl::_V1::detail::RoundedRangeKernel<sycl::_V1::item<1, true>, 1, main::'lambda'(sycl::_V1::handler&)::operator()(sycl::_V1::handler&) const::'lambda'(sycl::_V1::id<1>)>)
>>> referenced by lto.tmp:(typeinfo name for sycl::_V1::detail::RoundedRangeKernel<sycl::_V1::item<1, true>, 1, main::'lambda'(sycl::_V1::handler&)::operator()(sycl::_V1::handler&) const::'lambda'(sycl::_V1::id<1>)>)
>>> referenced by lto.tmp:(_ZTSN4sycl3_V16detail18RoundedRangeKernelINS0_4itemILi1ELb1EEELi1EZZ4mainENKUlRNS0_7handlerEE_clES6_EUlNS0_2idILi1EEEE_EE_with_offset)
>>> referenced 241 more times
llvm-foreach: 
clang-16: error: amdgcn-link command failed with exit code 1 (use -v to see invocation)

error: command failed with exit status: 1
```

**Comment by bader** [comment]
I hope https://github.com/intel/llvm-test-suite/commit/178db0d761ab7d3aa81f629a7a56990bfdcafd38 has fixed the issue with CUDA. We need to check intel/llvm pre-commits results.

**Comment by bader** [comment]
I see that #8058 is using https://github.com/intel/llvm-test-suite/commit/178db0d761ab7d3aa81f629a7a56990bfdcafd38. It doesn't fix CUDA and the test doesn't work on AMD.

As this test fails in each pre-commit for a few days already. I suggest we revert https://github.com/intel/llvm-test-suite/commit/178db0d761ab7d3aa81f629a7a56990bfdcafd38 and https://github.com/intel/llvm/pull/7959 let @jinge90 to debug this issue.

@aelovikov-intel, could you revert patches, please?

**Comment by bader** [comment]
> > > My best guess, that #7959 also required the test update, [intel/llvm-test-suite#1495](https://github.com/intel/llvm-test-suite/pull/1495).
> > 
> > 
> > Pre-commit for #7959 has passed w/o llvm-test-suite modifications. 🤔
> 
> Well, I still don't really understand the root cause of the issue, but in #7917 'verify with [intel/llvm-test-suite#1495](https://github.com/intel/llvm-test-suite/pull/1495) ' has passed. May be modification to the test hides the real issue?

@MrSidims, "verify with" doesn't cover CUDA and HIP platforms.

**Comment by aelovikov-intel** [comment]
> @aelovikov-intel, could you revert patches, please?

https://github.com/intel/llvm-test-suite/pull/1529
https://github.com/intel/llvm/pull/8061

**Comment by bader** [comment]
> > @aelovikov-intel, could you revert patches, please?
> 
> [intel/llvm-test-suite#1529](https://github.com/intel/llvm-test-suite/pull/1529) #8061

Thank you!
I merged these PR. Could you merge sycl branch to your https://github.com/intel/llvm/pull/8058 to re-start pre-commit testing? I hope it will pass.

**Comment by aelovikov-intel** [comment]
> Could you merge sycl branch to your #8058 to re-start pre-commit testing?

Done

**Comment by bader** [comment]
> > Could you merge sycl branch to your #8058 to re-start pre-commit testing?
> 
> Done

I see that the test still fails. I reverted two more patches https://github.com/intel/llvm-test-suite/pull/1520 and https://github.com/intel/llvm-test-suite/pull/1509. I hope this should resolve pre-commit testing issues.

**Comment by GeorgeWeb** [comment]
Hey @jinge90
I've investigated the original failure and this solution seems to be correct.
The check was originally verifying the wrong-way around setting leading to the error state being set for when values are indeed NAN rather than when they are not. I believe the proposed solution in [#1568](https://github.com/intel/llvm-test-suite/pull/1568) is OK.
